import 'dart:convert';

import 'package:flutter/services.dart';

import '../data/models/app_state.dart';
import 'day_plan_source.dart';
import 'foods.dart';
import 'i18n.dart';

/// The bundled dish catalogue — 60 real meals, each a list of catalogue foods with a job.
///
/// The planner prefers the user's own recipes to anything here, and should: a meal somebody
/// wrote down is in their words, made of food they buy. This exists for the fortnight before
/// there are any. A profile on its first day has an empty recipe book, and the alternative to
/// this is the category assembly in `day_plan.dart` — which hits the target exactly and
/// proposes cheese, rice and beetroot as though that were a meal.
///
/// Structured like [Foods] down to loading from a bundled asset, for the same reason: the app
/// works with no network at all. Generated by tool/gen_dishes.mjs from tool/dishes_seed.tsv.

/// The kitchens the catalogue is tagged for. Must match `CUISINES` in tool/gen_dishes.mjs.
const cuisines = <String>[
  'generic',
  'mediterranean',
  'european',
  'latin',
  'asian',
  'indian',
  'middleeastern',
];

/// English display names; these strings are the i18n keys.
const cuisineName = <String, String>{
  'generic': 'Anything',
  'mediterranean': 'Mediterranean',
  'european': 'European',
  'latin': 'Latin American',
  'asian': 'East Asian',
  'indian': 'Indian',
  'middleeastern': 'Middle Eastern',
};

/// Which kitchen to cook from when nobody has said.
///
/// The interface language is the best guess available and it is a good one: somebody running
/// the app in Italian is far more likely to want pasta than congee. It is only a default —
/// `NutritionGoal.cuisine` overrules it the moment the user picks — and it is deliberately not
/// stored, so changing the app's language moves it rather than leaving a stale copy behind.
const _cuisineOfLang = <String, String>{
  'es': 'mediterranean',
  'it': 'mediterranean',
  'fr': 'mediterranean',
  'pt': 'mediterranean',
  'de': 'european',
  'pl': 'european',
  'ru': 'european',
  'tr': 'middleeastern',
  'zh': 'asian',
  'ko': 'asian',
  'hi': 'indian',
};

/// The kitchen this profile cooks from.
String cuisineOf(AppState s) {
  final chosen = s.nutrition.goal.cuisine;
  if (chosen != null && cuisines.contains(chosen)) return chosen;
  return _cuisineOfLang[s.lang] ?? 'generic';
}

/// One dish: what it is called, when it is eaten, and what it is made of.
class Dish {
  const Dish({
    required this.id,
    required this.n,
    required this.slots,
    required this.cuisines,
    required this.parts,
  });

  final String id;

  /// Display name, and its own i18n key.
  final String n;

  /// Lowercased slot names — 'breakfast', 'lunch', 'snack', 'dinner'.
  final List<String> slots;

  final List<String> cuisines;

  final List<MealPart> parts;

  /// Whether this belongs in a slot named [slot], an English name from `mealSplit`.
  ///
  /// A split with a shape the table has no name for — 'All day', or a numbered 'Meal 3' from a
  /// hand-edited state — matches everything, because there is nothing to disagree with.
  bool fitsSlot(String slot) {
    final key = slot.toLowerCase();
    const known = {'breakfast', 'lunch', 'snack', 'dinner'};
    return !known.contains(key) || slots.contains(key);
  }

  static Dish? fromJson(Map<String, dynamic> j) {
    final parts = <MealPart>[];
    for (final raw in (j['parts'] is List ? j['parts'] as List : const [])) {
      if (raw is! Map) continue;
      final p = Map<String, dynamic>.from(raw);
      final food = foods[asStr(p['fid'])];
      // A dish naming a food this build does not carry is skipped rather than rendered as a
      // blank row. The generator refuses to emit one, so this only fires on a catalogue from a
      // newer build arriving in an older one.
      if (food == null) continue;
      final role = PartRole.values.where((r) => r.name == asStr(p['role'])).firstOrNull;
      if (role == null) continue;
      final grams = asNumOr(p['g'], 0);
      if (grams <= 0) continue;
      parts.add((base: food.portion(grams), role: role, step: asNum(p['step'])));
    }
    if (parts.length < 2) return null;
    return Dish(
      id: asStr(j['id']) ?? '',
      n: asStr(j['n']) ?? '',
      slots: [for (final s in (j['slots'] as List? ?? const [])) '$s'],
      cuisines: [for (final c in (j['cuisines'] as List? ?? const [])) '$c'],
      parts: parts,
    );
  }

  /// This dish as something the planner can resize. The name is translated here, once, so a
  /// proposal carries a name in the user's language without the planner knowing about i18n.
  PlanCandidate get candidate => (name: t(n), slot: null, parts: parts);
}

class Dishes {
  Dishes._();

  static final Dishes instance = Dishes._();

  final List<Dish> _db = [];

  List<Dish> get db => List.unmodifiable(_db);

  bool get isLoaded => _db.isNotEmpty;

  /// Loads the catalogue, or leaves it empty.
  ///
  /// Empty is a working state, not a broken one: `buildDayPlan` falls back to assembling a meal
  /// out of categories and behaves exactly as it did before this file existed. Throwing here
  /// would take down every test that forgot a `setUpAll` and every screen that renders a plan,
  /// to save a feature that has a fallback.
  Future<void> load() async {
    if (isLoaded) return;
    try {
      final raw = jsonDecode(await rootBundle.loadString('assets/data/dishes.json'));
      if (raw is! List) return;
      for (final e in raw) {
        if (e is! Map) continue;
        final dish = Dish.fromJson(Map<String, dynamic>.from(e));
        if (dish != null) _db.add(dish);
      }
    } catch (_) {
      // No catalogue. The planner has a fallback and the app has a day to plan.
    }
  }

  /// How many dishes a kitchen needs in a slot before "show me another" means anything.
  static const _enoughToVary = 3;

  /// Dishes that could be this slot, the user's own kitchen first.
  ///
  /// Three groups rather than one sorted list, and rotated within a group by the caller, for the
  /// reason `_pool` in `day_plan.dart` gives: a seed that rotates across a concatenated list
  /// walks straight past the part the ordering was for.
  ///
  /// The [_enoughToVary] rule is what makes a sixty-dish catalogue cover seven kitchens without
  /// either failure mode. Merging the universal dishes into every kitchen outright drowns the
  /// small ones — asian is seven dishes against twenty-five generic, and a Korean profile got a
  /// day with nothing Korean in it. Keeping them strictly below is worse the other way: there is
  /// exactly one East Asian breakfast, so that profile was handed congee on every single seed
  /// and reshuffling did nothing at all. A kitchen too thin to vary within borrows what every
  /// kitchen has; one that can stand on its own is left to.
  ({List<Dish> mine, List<Dish> plain, List<Dish> rest}) forSlot(
    String slot, {
    required String cuisine,
  }) {
    final mine = <Dish>[];
    final plain = <Dish>[];
    final rest = <Dish>[];
    for (final d in _db) {
      if (!d.fitsSlot(slot)) continue;
      if (d.cuisines.contains(cuisine)) {
        mine.add(d);
      } else if (d.cuisines.contains('generic')) {
        plain.add(d);
      } else {
        rest.add(d);
      }
    }
    if (mine.length < _enoughToVary) {
      mine.addAll(plain);
      plain.clear();
    }
    return (mine: mine, plain: plain, rest: rest);
  }
}

/// Short alias, matching `foods` and `exdb`.
final dishes = Dishes.instance;
