// Extracts the openGym icon set out of components/Icon.jsx into Dart.
//
// The icons are hand-drawn on a 24×24 grid with the live area at 3…21, strokes only (except
// where a shape reads better solid), round caps and joins, and geometry snapped to .5 so it
// lands on pixel edges. Transcribing ~90 of those by hand would introduce exactly the drift
// the conventions exist to prevent, so the source of truth stays Icon.jsx and this script is
// re-runnable whenever it changes.
import { readFileSync, writeFileSync } from 'node:fs'

const src = readFileSync(new URL('../../openGym/frontend/src/components/Icon.jsx', import.meta.url), 'utf8')

const body = src.slice(src.indexOf('const P = {') + 'const P = {'.length, src.indexOf('\n}\n'))
const attrs = tag => Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map(m => [m[1], m[2]]))
const solid = a => a.fill === 'currentColor' && a.stroke === 'none'
const n = v => {
  const f = parseFloat(v)
  return Number.isInteger(f) ? `${f}` : `${f}`
}

const icons = []
for (const line of body.split('\n')) {
  const m = line.match(/^\s{2}(\w+):\s*(<.+>),\s*$/)
  if (!m) continue
  const [, name, jsx] = m
  const shapes = []
  for (const tag of jsx.matchAll(/<(path|circle|rect)\b([^>]*)\/>/g)) {
    const a = attrs(tag[2])
    const f = solid(a) ? ', filled: true' : ''
    if (tag[1] === 'path') shapes.push(`IconPath(${JSON.stringify(a.d)}${f})`)
    else if (tag[1] === 'circle') shapes.push(`IconCircle(${n(a.cx)}, ${n(a.cy)}, ${n(a.r)}${f})`)
    else shapes.push(`IconRect(${n(a.x)}, ${n(a.y)}, ${n(a.width)}, ${n(a.height)}, ${n(a.rx ?? 0)})`)
  }
  if (!shapes.length) throw new Error(`no shapes parsed for icon "${name}"`)
  icons.push([name, shapes])
}

// A few keys are aliases so call sites can say what they mean.
const aliases = [...src.matchAll(/^P\.(\w+)\s*=\s*P\.(\w+)$/gm)].map(m => [m[1], m[2]])

const out = `// GENERATED by tool/gen_icons.mjs from openGym/frontend/src/components/Icon.jsx.
// Do not edit by hand — re-run the script instead.
//
// openGym icon set — hand-drawn on a 24x24 grid, stroke-based, single weight. Every icon is
// painted with \`currentColor\` and \`1em\` sizing, so it inherits the text colour and optical
// size of whatever it sits in. No emoji anywhere in the chrome: emoji render differently on
// every platform, sit on their own baseline and cannot take a theme colour.
//
// Conventions, so a new icon never looks foreign next to an old one:
//   - 24x24 viewBox, live area 3..21 - 3px of optical padding all round
//   - strokes only (no fills) except where a shape reads better solid (starFill, dot)
//   - round caps + round joins, stroke width from IconStroke (1.7 default)
//   - geometry snapped to .5 so it lands on pixel edges at 24px
part of 'app_icon.dart';

const _icons = <String, List<IconShape>>{
${icons.map(([name, s]) => `  '${name}': [${s.join(', ')}],`).join('\n')}

  // aliases
${aliases.map(([a, t]) => `  '${a}': _${t},`).join('\n')}
};

${[...new Set(aliases.map(a => a[1]))].map(t => {
  const s = icons.find(i => i[0] === t)
  return `const _${t} = <IconShape>[${s[1].join(', ')}];`
}).join('\n')}
`

writeFileSync(new URL('../lib/ui/widgets/icon_paths.dart', import.meta.url), out)
console.log(`icon_paths.dart — ${icons.length} icons + ${aliases.length} aliases`)
console.log(icons.map(i => i[0]).join(' '))
