// GENERATED by tool/gen_icons.mjs from openGym/frontend/src/components/Icon.jsx.
// Do not edit by hand — re-run the script instead.
//
// openGym icon set — hand-drawn on a 24x24 grid, stroke-based, single weight. Every icon is
// painted with `currentColor` and `1em` sizing, so it inherits the text colour and optical
// size of whatever it sits in. No emoji anywhere in the chrome: emoji render differently on
// every platform, sit on their own baseline and cannot take a theme colour.
//
// Conventions, so a new icon never looks foreign next to an old one:
//   - 24x24 viewBox, live area 3..21 - 3px of optical padding all round
//   - strokes only (no fills) except where a shape reads better solid (starFill, dot)
//   - round caps + round joins, stroke width from IconStroke (1.7 default)
//   - geometry snapped to .5 so it lands on pixel edges at 24px
part of 'app_icon.dart';

const _icons = <String, List<IconShape>>{
  'house': [IconPath("M3.5 10.7 12 3.8l8.5 6.9M5.9 9.4V19a1.4 1.4 0 0 0 1.4 1.4h9.4A1.4 1.4 0 0 0 18.1 19V9.4")],
  'calendar': [IconRect(3.4, 5.2, 17.2, 15.4, 3.2), IconPath("M8.2 3.4v3.4M15.8 3.4v3.4M3.4 10.2h17.2")],
  'chart': [IconPath("M4.5 20.2V13M9.5 20.2V6.4M14.5 20.2v-5.1M19.5 20.2V9.6")],
  'magnifier': [IconCircle(11, 11, 7), IconPath("m20.5 20.5-4.4-4.4")],
  'gear': [IconPath("M20.48 10.59 20.48 13.41 18.58 13.72 17.87 15.43 19 17 17 19 15.43 17.87 13.72 18.58 13.41 20.48 10.59 20.48 10.28 18.58 8.57 17.87 7 19 5 17 6.13 15.43 5.42 13.72 3.52 13.41 3.52 10.59 5.42 10.28 6.13 8.57 5 7 7 5 8.57 6.13 10.28 5.42 10.59 3.52 13.41 3.52 13.72 5.42 15.43 6.13 17 5 19 7 17.87 8.57 18.58 10.28Z"), IconCircle(12, 12, 3.1)],
  'dumbbell': [IconRect(5.9, 7.9, 3.2, 8.2, 1.3), IconRect(14.9, 7.9, 3.2, 8.2, 1.3), IconPath("M9.1 12h5.8M3.6 9.9v4.2M20.4 9.9v4.2")],
  'barbell': [IconPath("M2.9 12h18.2M7.4 7.4v9.2M9.8 9.3v5.4M16.6 7.4v9.2M14.2 9.3v5.4")],
  'figureRun': [IconCircle(14.2, 4.9, 1.9), IconPath("M13.4 9.1 9.6 11.4l1.7 3.3-2.4 5.4M13.4 9.1l3.4 1.5 1.4 3.4M11.3 14.7l4.3.9 1.5 4.5M9.6 11.4 6 10.2")],
  'figureStrength': [IconCircle(12, 5.2, 2), IconPath("M12 8.4v5.6M12 14 9.2 20.5M12 14l2.8 6.5M8 10.6h8M5.4 9.1v3M18.6 9.1v3")],
  'scale': [IconRect(3.4, 4.4, 17.2, 16.2, 3.4), IconPath("M8.3 9.2a3.9 3.9 0 0 1 7.4 0"), IconPath("M12 9.2v2.5M8.9 16.2h6.2")],
  'flame': [IconPath("M12 20.4c3.2 0 5.4-2.1 5.4-5.1 0-3.9-3.4-5.6-2.6-9.8-2.5.8-4 2.9-4 5.1 0 1-.5 1.6-1.2 1.6-.8 0-1.2-.7-1.2-1.8-1.1 1.2-1.8 2.9-1.8 4.9 0 3 2.2 5.1 5.4 5.1Z")],
  'timer': [IconCircle(12, 13.4, 7.2), IconPath("M12 9.6v3.8h2.8M9.6 3.4h4.8")],
  'clock': [IconCircle(12, 12, 8.2), IconPath("M12 7.4V12l3.1 1.9")],
  'trophy': [IconPath("M7.6 4h8.8v4.6a4.4 4.4 0 0 1-8.8 0Z"), IconPath("M7.6 5.6H4.9v1.5a3 3 0 0 0 2.9 3M16.4 5.6h2.7v1.5a3 3 0 0 1-2.9 3M12 13v3.4M8.6 20.4h6.8l-.7-4H9.3Z")],
  'medal': [IconCircle(12, 14.8, 5.2), IconCircle(12, 14.8, 1.9), IconPath("M9.1 9.9 6.4 3.6M14.9 9.9l2.7-6.3")],
  'target': [IconCircle(12, 12, 8.2), IconCircle(12, 12, 4.6), IconCircle(12, 12, 1.1)],
  'star': [IconPath("m12 3.9 2.6 5.3 5.8.8-4.2 4.1 1 5.8-5.2-2.7-5.2 2.7 1-5.8-4.2-4.1 5.8-.8Z")],
  'starFill': [IconPath("m12 3.9 2.6 5.3 5.8.8-4.2 4.1 1 5.8-5.2-2.7-5.2 2.7 1-5.8-4.2-4.1 5.8-.8Z", filled: true)],
  'crown': [IconPath("M4.2 17.6h15.6M4.2 17.6 3.4 7.2l4.6 3.2L12 4.6l4 5.8 4.6-3.2-.8 10.4Z")],
  'bolt': [IconPath("M13.4 3.4 5.6 13.6h5.2l-.2 7 7.8-10.2h-5.2Z")],
  'shield': [IconPath("M12 3.6 5 6.2v5.5c0 4 2.9 7.5 7 8.7 4.1-1.2 7-4.7 7-8.7V6.2Z")],
  'heart': [IconPath("M12 20c-.4 0-.8-.1-1-.4l-6.2-6a4.6 4.6 0 0 1 0-6.6 4.4 4.4 0 0 1 6.2 0l1 1 1-1a4.4 4.4 0 0 1 6.2 0 4.6 4.6 0 0 1 0 6.6l-6.2 6c-.2.3-.6.4-1 .4Z")],
  'rocket': [IconPath("M12 3.6c2.8 2.5 4.2 5.7 4.2 9.1v4.5H7.8v-4.5c0-3.4 1.4-6.6 4.2-9.1Z"), IconCircle(12, 10.3, 1.8), IconPath("M7.8 14 5.2 16.6v3.8l2.6-2M16.2 14l2.6 2.6v3.8l-2.6-2")],
  'sparkles': [IconPath("m8.4 3.8 1.1 2.9 2.9 1.1-2.9 1.1-1.1 2.9-1.1-2.9L4.4 7.8l2.9-1.1Z"), IconPath("m16.2 12.4.8 2.1 2.1.8-2.1.8-.8 2.1-.8-2.1-2.1-.8 2.1-.8Z")],
  'lightbulb': [IconPath("M9.2 16.4a5.6 5.6 0 1 1 5.6 0v1.8H9.2Z"), IconPath("M10 20.6h4")],
  'arm': [IconCircle(7, 5.8, 1.9), IconPath("M7 8.8v4.6l-1.2 6.2M7 11.4l4.4 1.9"), IconRect(12.2, 10.8, 2.3, 5, 0.9), IconRect(15.9, 10.8, 2.3, 5, 0.9), IconPath("M14.5 13.3h1.4")],
  'abs': [IconPath("M7.8 4.4h8.4v10.4a4.2 4.2 0 0 1-8.4 0Z"), IconPath("M12 6.2v9M9 8.9h2.2M12.8 8.9h2.2M9 11.6h2.2M12.8 11.6h2.2M9.3 14.2h1.9M12.9 14.2h1.9")],
  'legs': [IconPath("M8.4 4.2h7.2"), IconPath("M9.9 4.2v4.9l-1.3 4.4.9 6.3M14.1 4.2v4.9l1.3 4.4-.9 6.3"), IconPath("M7.7 19.8h2.6M13.7 19.8h2.6")],
  'pullup': [IconPath("M3.6 5.1h16.8M8.5 5.5v2.3M15.5 5.5v2.3"), IconCircle(12, 9.6, 1.8), IconPath("m8.5 7.8 3.5 5 3.5-5M12 13.3v3.9M12 17.2l-2.1 3.2M12 17.2l2.1 3.2")],
  'kettlebell': [IconPath("M9.5 11V9.6a2.5 2.5 0 0 1 5 0V11"), IconPath("M14.9 11.8c2.2 1.5 3.6 3.9 3.6 6.4a1.6 1.6 0 0 1-1.6 1.6H7.1a1.6 1.6 0 0 1-1.6-1.6c0-2.5 1.4-4.9 3.6-6.4Z")],
  'plate': [IconCircle(12, 12, 8.2), IconCircle(12, 12, 2.7)],
  'machine': [IconPath("M12 3.6v3.1"), IconRect(6.6, 6.7, 10.8, 12.9, 1.9), IconPath("M9 10.1h6M9 13.2h6M9 16.3h6")],
  'bike': [IconCircle(6.2, 16.2, 3.5), IconCircle(17.8, 16.2, 3.5), IconPath("m6.2 16.2 4.3-7.4h4.9l2.4 7.4M9.3 8.8h4.5M13.8 8.8l-2.6 7.4")],
  'swim': [IconCircle(8.8, 8.2, 1.8), IconPath("m10.9 10 4.6-2.2 3.3 3.4"), IconPath("M3.5 15.6c1.6-1.3 3.1-1.3 4.7 0s3.1 1.3 4.7 0 3.1-1.3 4.7 0c.9.7 1.7.9 2.6.5")],
  'boxing': [IconPath("M7.6 8.6A4.6 4.6 0 0 1 12.2 4h1.6a5.4 5.4 0 0 1 5.4 5.4v2.4a3 3 0 0 1-3 3H7.6Z"), IconPath("M7.6 14.8v2.3a2.6 2.6 0 0 0 2.6 2.6h5.2a2.6 2.6 0 0 0 2.6-2.6v-2.3"), IconPath("M7.6 9.8H6.3a1.8 1.8 0 0 0 0 3.6h1.3")],
  'stretch': [IconCircle(14.4, 5.4, 1.9), IconPath("M14.4 8.2c-3 1.4-5 4-5.8 7.4"), IconPath("M8.6 15.6 6.2 20M8.6 15.6l4.6 4.4"), IconPath("M12.6 9.6 18 12")],
  'plus': [IconPath("M12 5.2v13.6M5.2 12h13.6")],
  'minus': [IconPath("M5.2 12h13.6")],
  'check': [IconPath("m4.8 12.6 4.8 4.8L19.2 6.8")],
  'checkCircle': [IconCircle(12, 12, 8.2), IconPath("m8.2 12.2 2.7 2.7 5.1-5.4")],
  'xmark': [IconPath("M6.2 6.2 17.8 17.8M17.8 6.2 6.2 17.8")],
  'pencil': [IconPath("M17.1 3.9a2.1 2.1 0 0 1 3 3l-9.9 9.9-4 1 1-4Z"), IconPath("m15.1 5.9 3 3")],
  'trash': [IconPath("M4.8 6.6h14.4M9.4 6.6V4.8a1.2 1.2 0 0 1 1.2-1.2h2.8a1.2 1.2 0 0 1 1.2 1.2v1.8"), IconPath("M6.6 6.6 7.4 19a1.6 1.6 0 0 0 1.6 1.4h6a1.6 1.6 0 0 0 1.6-1.4l.8-12.4"), IconPath("M10.4 10.2v6.4M13.6 10.2v6.4")],
  'link': [IconPath("M10.2 13.8a3.6 3.6 0 0 0 5.4.4l2.6-2.6a3.6 3.6 0 0 0-5.1-5.1l-1.5 1.5"), IconPath("M13.8 10.2a3.6 3.6 0 0 0-5.4-.4l-2.6 2.6a3.6 3.6 0 0 0 5.1 5.1l1.5-1.5")],
  'play': [IconPath("M8.4 5.6 18 12l-9.6 6.4Z")],
  'pause': [IconPath("M9.4 5.8v12.4M14.6 5.8v12.4")],
  'reset': [IconPath("M4.4 12a7.6 7.6 0 1 0 2.3-5.4"), IconPath("M4 4.4v4.4h4.4")],
  'bell': [IconPath("M6.6 10.4a5.4 5.4 0 0 1 10.8 0c0 4 1.4 5.6 1.4 5.6H5.2s1.4-1.6 1.4-5.6Z"), IconPath("M10.1 19.2a2.1 2.1 0 0 0 3.8 0")],
  'bellSlash': [IconPath("M8.1 6.6a5.4 5.4 0 0 1 9.3 3.8c0 4 1.4 5.6 1.4 5.6H9.4M6.6 16H5.2s1.4-1.6 1.4-5.6v-.6"), IconPath("M10.1 19.2a2.1 2.1 0 0 0 3.8 0M4 3.6l16 16.8")],
  'chevronRight': [IconPath("m9.6 5.6 6.6 6.4-6.6 6.4")],
  'chevronLeft': [IconPath("m14.4 5.6-6.6 6.4 6.6 6.4")],
  'chevronDown': [IconPath("m5.6 9.4 6.4 6.2 6.4-6.2")],
  'chevronUp': [IconPath("m5.6 14.6 6.4-6.2 6.4 6.2")],
  'arrowUp': [IconPath("M12 19.6V4.4M6.2 10.6 12 4.4l5.8 6.2")],
  'arrowDown': [IconPath("M12 4.4v15.2M6.2 13.4 12 19.6l5.8-6.2")],
  'expand': [IconPath("M14.4 4.4h5.2v5.2M9.6 19.6H4.4v-5.2M19.6 4.4 13.8 10.2M4.4 19.6l5.8-5.8")],
  'minimize': [IconPath("M19.6 9.6h-5.2V4.4M4.4 14.4h5.2v5.2M14.4 9.6l5.2-5.2M9.6 14.4l-5.2 5.2")],
  'person': [IconCircle(12, 8, 3.8), IconPath("M4.8 20.4a7.2 7.2 0 0 1 14.4 0")],
  'personCircle': [IconCircle(12, 12, 8.4), IconCircle(12, 10, 2.9), IconPath("M6.6 18.4a5.8 5.8 0 0 1 10.8 0")],
  'clipboard': [IconRect(5.4, 4.8, 13.2, 15.8, 2.6), IconPath("M9 4.8a1.6 1.6 0 0 1 1.6-1.6h2.8A1.6 1.6 0 0 1 15 4.8v1.4H9Z"), IconPath("M9.2 11.6h5.6M9.2 15.2h4")],
  'list': [IconPath("M8.4 6.6h11.2M8.4 12h11.2M8.4 17.4h11.2M4.6 6.6h.01M4.6 12h.01M4.6 17.4h.01")],
  'folder': [IconPath("M3.6 7.4a2 2 0 0 1 2-2h3.1l2 2.4h6.7a2 2 0 0 1 2 2v7.8a2 2 0 0 1-2 2H5.6a2 2 0 0 1-2-2Z")],
  'globe': [IconCircle(12, 12, 8.2), IconPath("M3.8 12h16.4M12 3.8c2.1 2.2 3.2 5.1 3.2 8.2s-1.1 6-3.2 8.2c-2.1-2.2-3.2-5.1-3.2-8.2s1.1-6 3.2-8.2Z")],
  'moon': [IconPath("M19.4 14.2A7.8 7.8 0 0 1 9.8 4.6a8.2 8.2 0 1 0 9.6 9.6Z")],
  'sun': [IconCircle(12, 12, 4.4), IconPath("M12 3.6v2M12 18.4v2M20.4 12h-2M5.6 12h-2M17.94 6.06l-1.42 1.42M7.48 16.52l-1.42 1.42M17.94 17.94l-1.42-1.42M7.48 7.48 6.06 6.06")],
  'key': [IconCircle(8.2, 15.8, 3.8), IconPath("m10.9 13.1 8-8M16.6 7.4l2 2M14.6 9.4l2 2")],
  'lock': [IconRect(5, 10.4, 14, 10, 2.8), IconPath("M8.4 10.4V7.8a3.6 3.6 0 0 1 7.2 0v2.6")],
  'download': [IconPath("M12 3.8v11.4M7.6 11.2 12 15.6l4.4-4.4M4.6 19.4h14.8")],
  'upload': [IconPath("M12 15.6V4.2M7.6 8.2 12 3.8l4.4 4.4M4.6 19.4h14.8")],
  'wrench': [IconPath("M15.2 3.9a5 5 0 0 0-4.8 6.6l-6 6a2.1 2.1 0 0 0 3 3l6-6a5 5 0 0 0 6.1-6.3l-2.9 2.9-2.8-.7-.7-2.8Z")],
  'flag': [IconPath("M6 20.4V4.2"), IconPath("M6.4 5.2h13v9.2h-13"), IconPath("M12.9 5.2v9.2M6.4 9.8h13")],
  'chartLine': [IconPath("M3.6 20.2V4.4M3.6 20.2h16.8M6.4 16.4l3.9-4.8 3.1 2.7 5.2-6.6")],
  'dot': [IconCircle(12, 12, 4.2, filled: true)],
  'history': [IconPath("M4.5 12.2a7.6 7.6 0 1 0 2.5-5.6"), IconPath("M4.1 4.4v4.3h4.3"), IconPath("M12 8.3v4.2l3.1 1.9")],
  'signOut': [IconPath("M14.2 4.6H7a1.9 1.9 0 0 0-1.9 1.9v11a1.9 1.9 0 0 0 1.9 1.9h7.2"), IconPath("m16.8 8.4 3.6 3.6-3.6 3.6M20.4 12H10.2")],
  'shuffle': [IconPath("M3.6 7.2h2.9c1.6 0 2.8.9 3.8 2.4l3 4.8c1 1.5 2.2 2.4 3.8 2.4h2.9M3.6 16.8h2.9c1.6 0 2.8-.9 3.8-2.4l.7-1.1M15.6 9.9l.7-1.1c1-1.5 2.2-2.4 3.8-2.4h1.9"), IconPath("m17.9 4.3 2.8 2.1-2.8 2.1M17.9 14.7l2.8 2.1-2.8 2.1")],
  'info': [IconCircle(12, 12, 8.2), IconPath("M12 11v5.4"), IconCircle(12, 7.9, 0.9, filled: true)],

  // aliases
  'search': _magnifier,
  'settings': _gear,
  'exercises': _magnifier,
  'weight': _scale,
  'streak': _flame,
  'done': _check,
};

const _magnifier = <IconShape>[IconCircle(11, 11, 7), IconPath("m20.5 20.5-4.4-4.4")];
const _gear = <IconShape>[IconPath("M20.48 10.59 20.48 13.41 18.58 13.72 17.87 15.43 19 17 17 19 15.43 17.87 13.72 18.58 13.41 20.48 10.59 20.48 10.28 18.58 8.57 17.87 7 19 5 17 6.13 15.43 5.42 13.72 3.52 13.41 3.52 10.59 5.42 10.28 6.13 8.57 5 7 7 5 8.57 6.13 10.28 5.42 10.59 3.52 13.41 3.52 13.72 5.42 15.43 6.13 17 5 19 7 17.87 8.57 18.58 10.28Z"), IconCircle(12, 12, 3.1)];
const _scale = <IconShape>[IconRect(3.4, 4.4, 17.2, 16.2, 3.4), IconPath("M8.3 9.2a3.9 3.9 0 0 1 7.4 0"), IconPath("M12 9.2v2.5M8.9 16.2h6.2")];
const _flame = <IconShape>[IconPath("M12 20.4c3.2 0 5.4-2.1 5.4-5.1 0-3.9-3.4-5.6-2.6-9.8-2.5.8-4 2.9-4 5.1 0 1-.5 1.6-1.2 1.6-.8 0-1.2-.7-1.2-1.8-1.1 1.2-1.8 2.9-1.8 4.9 0 3 2.2 5.1 5.4 5.1Z")];
const _check = <IconShape>[IconPath("m4.8 12.6 4.8 4.8L19.2 6.8")];
